version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastify-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-ui
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
